### ISSUE TITLE
As a user I want to be able to do an interactive tutorial, so that I know how the game works and looks.

### ISSUE THREAD

**Issue by carolernst-uzh** [sopra-fs23-group-37/server#15]
- There is a button to start an interactive tutorial on the home screen.
- A game screen is displayed, with prompts that guide the user through possible moves and explain screen components and transitions. 
- It is possible to leave the tutorial at any time by clicking on the leave button.
- After the tutorial is over, the user is redirected to the home screen.

- [x] sopra-fs23-group-37/client#186
- [x] sopra-fs23-group-37/client#185
- [ ] sopra-fs23-group-37/client#187
- [x] sopra-fs23-group-37/client#190
- [x] sopra-fs23-group-37/client#188
- [x] #188
