### ISSUE TITLE
As an user I want to see my statistics, so that I know how many games I won and how many I lost on the home screen.

### ISSUE THREAD

**Issue by carolernst-uzh** [sopra-fs23-group-37/server#17]
Criteria
- [ ] After successfully login in, the user sees how many games he/she won, lost and aborted on the home screen.
- [ ] The Players statistics are saved on the database.
- [ ] The Players statistics cannot be changed manually and are updated automatically with each game played.

Tasks
- [x] sopra-fs23-group-37/server#138
- [x] sopra-fs23-group-37/client#141
- [x] sopra-fs23-group-37/client#142
- [x] https://github.com/sopra-fs23-group-37/server/issues/150
