### ISSUE TITLE
As a player, I want to have a new round automatically set up with 8 cards per hand and 4 cards on the table, so that my opponent and I can start playing the round.

### ISSUE THREAD

**Issue by carolernst-uzh** [sopra-fs23-group-37/server#3]
**Acceptance Criteria**
- [ ] When a new round is started (new game or new round in existing game) each player should get 8 randomly drawn cards from the deck displayed in their hand.
- [ ] The cards in each player's hand are visible to the player, but not their opponent.
- [ ] When a new round is started, 4 randomly drawn cards should be placed face-up on the table.
- [ ] If the round is the first one of a game, then 2 additional cards are drawn, one for each player, and placed face-up on the table. The player with the higher card will be indicated as the starting player. The cards are put back in the deck in a random location.
- [ ] Cards on the table should be visible to both the player and their opponent.
- [ ] A playing deck API should be used to manage randomly drawing cards from a deck, without repeating cards.

**Development Tasks**
- [x] sopra-fs23-group-37/client#6
- [x] sopra-fs23-group-37/client#7
- [x] sopra-fs23-group-37/client#8
- [x] sopra-fs23-group-37/client#9
- [x] https://github.com/sopra-fs23-group-37/client/issues/55
- [x] sopra-fs23-group-37/server#34
- [x] sopra-fs23-group-37/server#35
- [x] sopra-fs23-group-37/server#36
