### ISSUE TITLE
As a player I want to be able to select a card from my hand and then place it on the playing field, so that I can make the appropriate move.

### ISSUE THREAD

**Issue by carolernst-uzh** [sopra-fs23-group-37/server#4]
**Acceptance Criteria**
- [ ] The player's hand is displayed on the screen.
- [ ] There is an indicator showing whether it is the player’s move, or their opponent’s move.
- [ ] If it is the opponent’s move, no selections are possible.
- [ ] If it is the current player’s move, clicking on a card in the hand selects that card.
- [ ] Clicking on one or multiple cards on the table moves the selected cards to the player's pile if the move is legal.
- [ ] Clicking on a dedicated empty space places the card on the playing field.

**Development Tasks**
- [x] sopra-fs23-group-37/client#10
- [x] sopra-fs23-group-37/client#11
- [ ] sopra-fs23-group-37/client#12
- [x] sopra-fs23-group-37/server#40
- [x] sopra-fs23-group-37/server#41
- [x] sopra-fs23-group-37/server#60
- [x] sopra-fs23-group-37/server#61
