### ISSUE TITLE
As a player I want the round to end after all cards are played and the points being automatically awarded, so that I know what the current point total is.

### ISSUE THREAD

**Issue by carolernst-uzh** [sopra-fs23-group-37/server#6]
**Acceptance Criteria**
- [ ] When both players are out of cards and there are no more cards left in the deck, the round ends.
- [ ] If there are cards remaining on the table, these are awarded to the player who last matched and picked up cards.
- [ ] The game shows how the points are awarded to both players.
- [ ] The points are added to the total.
- [ ] The game cleans up the playing field and moves to the next round setup.

**Devlopment Tasks**
- [ ] sopra-fs23-group-37/client#14
- [x] sopra-fs23-group-37/client#15
- [x] sopra-fs23-group-37/server#46
- [x] sopra-fs23-group-37/server#47
