### ISSUE TITLE
As a player I want to be able to cancel the game at any time, so that I can leave the game when I want to.

### ISSUE THREAD

**Issue by carolernst-uzh** [sopra-fs23-group-37/server#9]
**Acceptance Criteria**
- [ ] There is a button to leave the game, which the user can click to do so. 
- [ ] The player who left the game will be redirected to the home screen.
- [ ] The opponent of the player who left the game will get a pop-up notification that the player has left the game with an “ok” button. 
- [ ] After acknowledging the notification by clicking “ok” the opponent will also be redirected to the home screen. 

**Development Tasks**
- [x] sopra-fs23-group-37/client#19
- [ ] sopra-fs23-group-37/client#18
- [x] sopra-fs23-group-37/server#53
